const bancoDePerguntas = [
    
    { pergunta: "Quem foi o primeiro homem criado por Deus?", opcoes: ["Abel", "Adão", "Set", "Noé"], respostaCorreta: 1, nivel: 'facil', mes: 1 },
    { pergunta: "Qual é o primeiro livro da Bíblia?", opcoes: ["Êxodo", "Gênesis", "Levítico", "Mateus"], respostaCorreta: 1, nivel: 'facil', mes: 1 },
    { pergunta: "Quem construiu a arca?", opcoes: ["Moisés", "Abraão", "Noé", "Davi"], respostaCorreta: 2, nivel: 'facil', mes: 1 },
    { pergunta: "Qual o nome da esposa de Adão?", opcoes: ["Sara", "Rebeca", "Eva", "Raquel"], respostaCorreta: 2, nivel: 'facil', mes: 1 },
    { pergunta: "Quem matou seu próprio irmão no início da humanidade?", opcoes: ["Caim", "Lameque", "Enoque", "Jafé"], respostaCorreta: 0, nivel: 'facil', mes: 1 },
    { pergunta: "De quem Deus pediu o sacrifício do filho no monte Moriá?", opcoes: ["Noé", "Abraão", "Isaque", "Jacó"], respostaCorreta: 1, nivel: 'facil', mes: 1 },
    { pergunta: "Quem foi vendido pelos irmãos e foi para o Egito?", opcoes: ["Benjamin", "José", "Ruben", "Levi"], respostaCorreta: 1, nivel: 'facil', mes: 1 },
    { pergunta: "Como a terra foi inundada no dilúvio?", opcoes: ["Com chuva global e águas profundas", "Rio Nilo", "Rio Jordão", "Rio Eufrates"], respostaCorreta: 0, nivel: 'facil', mes: 1 },
    { pergunta: "Quem riu quando Deus disse que ela teria um filho na velhice?", opcoes: ["Raquel", "Sara", "Lia", "Rebeca"], respostaCorreta: 1, nivel: 'facil', mes: 1 },
    { pergunta: "Quantos filhos teve Jacó (que deram origem às tribos)?", opcoes: ["10", "12", "7", "3"], respostaCorreta: 1, nivel: 'facil', mes: 1 },

    { pergunta: "Quem foi o pai de Matusalém?", opcoes: ["Enoque", "Jarede", "Lameque", "Noé"], respostaCorreta: 0, nivel: 'medio', mes: 1 },
    { pergunta: "Qual o nome do rei de Salém que abençoou Abraão?", opcoes: ["Abimeleque", "Melquisedeque", "Faraó", "Jetro"], respostaCorreta: 1, nivel: 'medio', mes: 1 },
    { pergunta: "Quantos anos viveu Adão?", opcoes: ["930 anos", "969 anos", "777 anos", "800 anos"], respostaCorreta: 0, nivel: 'medio', mes: 1 },
    { pergunta: "Qual o nome do irmão mais velho de José?", opcoes: ["Simeão", "Judá", "Rúben", "Levi"], respostaCorreta: 2, nivel: 'medio', mes: 1 },
    { pergunta: "Onde a arca de Noé pousou?", opcoes: ["Monte Sinai", "Montes de Ararate", "Monte Nebo", "Monte Carmelo"], respostaCorreta: 1, nivel: 'medio', mes: 1 },
    { pergunta: "Quem era a mãe de Ismael, filho de Abraão?", opcoes: ["Sara", "Agar", "Quetura", "Milca"], respostaCorreta: 1, nivel: 'medio', mes: 1 },
    { pergunta: "Qual o significado do nome 'Abraão'?", opcoes: ["Pai de muitas nações", "Riso", "Aquele que luta com Deus", "Príncipe"], respostaCorreta: 0, nivel: 'medio', mes: 1 },
    { pergunta: "Quem interpretou os sonhos do Faraó no Egito?", opcoes: ["Daniel", "José", "Moisés", "Aarão"], respostaCorreta: 1, nivel: 'medio', mes: 1 },
    { pergunta: "Qual o nome do poço que Isaque cavou e cujos pastores disputaram?", opcoes: ["Berseba", "Eseque", "Beer-Laai-Rói", "Elim"], respostaCorreta: 1, nivel: 'medio', mes: 1 },
    { pergunta: "Quem foi a esposa de Isaque?", opcoes: ["Raquel", "Rebeca", "Zilpa", "Bila"], respostaCorreta: 1, nivel: 'medio', mes: 1 },

    { pergunta: "Qual o nome do vale onde ocorreu a batalha dos quatro reis contra os cinco?", opcoes: ["Vale de Sidim", "Vale de Elá", "Vale de Acor", "Vale de Josafá"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Quem foi o primogênito de Ismael?", opcoes: ["Quedar", "Nebaiote", "Midão", "Jokshan"], respostaCorreta: 1, nivel: 'dificil', mes: 1 },
    { pergunta: "Qual o nome do tio de Abraão, pai de Ló?", opcoes: ["Terá", "Harã", "Naor", "Serugue"], respostaCorreta: 1, nivel: 'dificil', mes: 1 },
    { pergunta: "Quantas pessoas da família de Jacó desceram para o Egito?", opcoes: ["70 pessoas", "50 pessoas", "100 pessoas", "12 pessoas"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Qual o nome egípcio que o Faraó deu a José?", opcoes: ["Zafenate-Paneia", "Trompete", "Afenate", "Potifar"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Quem era a mãe de Zilpa, serva de Lia?", opcoes: ["Não é mencionado na Bíblia", "Labão", "Suas", "Milca"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Qual o nome da cidade onde Ló se refugiou ao fugir de Sodoma?", opcoes: ["Zoar", "Hebrom", "Gerar", "Berseba"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Qual o nome do monte onde Abraão ofereceu o carneiro em lugar de Isaque?", opcoes: ["Moriá", "Sinai", "Horebe", "Nebo"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Quantos anos tinha José quando começou a governar o Egito?", opcoes: ["30 anos", "40 anos", "25 anos", "33 anos"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },
    { pergunta: "Qual o nome da filha de Lia que é mencionada em Gênesis 34?", opcoes: ["Diná", "Tamar", "Asenate", "Maalate"], respostaCorreta: 0, nivel: 'dificil', mes: 1 },


    
    
    { pergunta: "Quem foi colocado em um cesto de junco nas águas do rio Nilo?", opcoes: ["Moisés", "Sansão", "Samuel", "Davi"], respostaCorreta: 0, nivel: 'facil', mes: 2 },
    { pergunta: "Qual o mar que Deus abriu para o povo de Israel passar a seco?", opcoes: ["Mar Vermelho", "Mar Morto", "Mar da Galileia", "Mar Mediterrâneo"], respostaCorreta: 0, nivel: 'facil', mes: 2 },
    { pergunta: "Quem foi o irmão de Moisés que o ajudou a falar com o Faraó?", opcoes: ["Josué", "Calebe", "Aarão", "Hur"], respostaCorreta: 2, nivel: 'facil', mes: 2 },
    { pergunta: "Quantas pragas Deus enviou ao Egito?", opcoes: ["7", "10", "12", "3"], respostaCorreta: 1, nivel: 'facil', mes: 2 },
    { pergunta: "Onde Deus entregou as tábuas da Lei a Moisés?", opcoes: ["Monte Sinai", "Monte Carmelo", "Monte das Oliveiras", "Monte Moriá"], respostaCorreta: 0, nivel: 'facil', mes: 2 },
    { pergunta: "Qual alimento milagroso caía do céu no deserto para alimentar os israelitas?", opcoes: ["Pão comum", "Maná", "Trigo", "Mel"], respostaCorreta: 1, nivel: 'facil', mes: 2 },
    { pergunta: "Qual o nome da esposa de Moisés?", opcoes: ["Zípora", "Ester", "Rute", "Débora"], respostaCorreta: 0, nivel: 'facil', mes: 2 },
    { pergunta: "Quem foi o líder que conduziu o povo para dentro da Terra Prometida após Moisés?", opcoes: ["Calebe", "Josué", "Pinhas", "Gideão"], respostaCorreta: 1, nivel: 'facil', mes: 2 },
    { pergunta: "Qual cidade teve suas muralhas derrubadas após o povo rodear por 7 dias?", opcoes: ["Jerusalém", "Jericó", "Ai", "Samaria"], respostaCorreta: 1, nivel: 'facil', mes: 2 },
    { pergunta: "Quem escondeu os espias israelitas em Jericó?", opcoes: ["Raabe", "Débora", "Jael", "Vasti"], respostaCorreta: 0, nivel: 'facil', mes: 2 },

    { pergunta: "Qual o nome do sogro de Moisés, sacerdote de Midiã?", opcoes: ["Jetro (Reuel)", "Labão", "Potifar", "Eli"], respostaCorreta: 0, nivel: 'medio', mes: 2 },
    { pergunta: "O que os israelitas construíram no deserto para adoração que podia ser transportado?", opcoes: ["O Templo", "O Tabernáculo", "A Sinagoga", "O Altar de Pedra"], respostaCorreta: 1, nivel: 'medio', mes: 2 },
    { pergunta: "Qual o nome do monte onde Moisés morreu?", opcoes: ["Nebo", "Sinai", "Horebe", "Tabor"], respostaCorreta: 0, nivel: 'medio', mes: 2 },
    { pergunta: "Qual tribo de Israel não recebeu porção de terra pois o Senhor era a sua herança?", opcoes: ["Judá", "Levi", "Benjamim", "Dã"], respostaCorreta: 1, nivel: 'medio', mes: 2 },
    { pergunta: "Quem pecou pegando do anátema (objeto proibido) na tomada de Jericó?", opcoes: ["Acã", "Geazi", "Corá", "Datan"], respostaCorreta: 0, nivel: 'medio', mes: 2 },
    { pergunta: "Qual mulher guerreira e juíza de Israel liderou Baraque na batalha contra Sisera?", opcoes: ["Débora", "Jael", "Hulda", "Abigail"], respostaCorreta: 0, nivel: 'medio', mes: 2 },
    { pergunta: "Quem matou o comandante Sisera cravando uma estaca em sua cabeça?", opcoes: ["Débora", "Jael", "Rute", "Ester"], respostaCorreta: 1, nivel: 'medio', mes: 2 },
    { pergunta: "Qual juiz derrotou os midianitas com apenas 300 homens usando trombetas e cântaros?", opcoes: ["Sansão", "Gideão", "Jefté", "Eúde"], respostaCorreta: 1, nivel: 'medio', mes: 2 },
    { pergunta: "Qual o nome da moabita que se tornou bisavó do rei Davi?", opcoes: ["Orfa", "Rute", "Naomi", "Noemi"], respostaCorreta: 1, nivel: 'medio', mes: 2 },
    { pergunta: "Quem era a mãe de Samuel?", opcoes: ["Penina", "Ana", "Eli", "Ester"], respostaCorreta: 1, nivel: 'medio', mes: 2 },

    { pergunta: "Qual o nome do líder dos amonitas derrotado por Jefté?", opcoes: ["Eglon", "O rei amonita não tem nome específico citado na história", "Balaque", "Sicon"], respostaCorreta: 1, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do vale onde o sol parou a pedido de Josué?", opcoes: ["Vale de Aijalom", "Vale de Elá", "Vale de Hinom", "Vale de Sucote"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Quantas cidades de refúgio foram estabelecidas na Terra Prometida?", opcoes: ["3", "6", "12", "40"], respostaCorreta: 1, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do cananeu esquerdino que matou o rei gordo Eglon de Moabe?", opcoes: ["Eúde", "Samgar", "Otniel", "Tola"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do gigante de Gate que tinha doze dedos nas mãos e nos pés?", opcoes: ["Não tem nome citado, apenas sua descrição", "Golias", "Isbi-Beno", "Saf"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do filho de Aarão que enfiou uma lança em Zimri e Cozbi para conter a praga?", opcoes: ["Nadabe", "Abiú", "Eleazar", "Pinhas"], respostaCorreta: 3, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do profeta que foi contratado para amaldiçoar Israel mas só abençoou?", opcoes: ["Balaão", "Samuel", "Natã", "Aías"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do pai de Calebe, o espião fiel?", opcoes: ["Jefoné", "Nun", "Zerah", "Cenaz"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome da cidade onde a arca da aliança ficou por muitos anos na casa de Abinadabe?", opcoes: ["Quiriate-Jarim", "Siló", "Nobe", "Gibeon"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },
    { pergunta: "Qual o nome do rei de Basã que foi derrotado por Moisés e era o último dos refains?", opcoes: ["Og", "Sicon", "Balaque", "Adoni-Zedeque"], respostaCorreta: 0, nivel: 'dificil', mes: 2 },


    
    
    { pergunta: "Quem foi o primeiro rei de Israel?", opcoes: ["Davi", "Saul", "Salomão", "Samuel"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Qual rei de Israel era um pastor de ovelhas e músico talentoso?", opcoes: ["Saul", "Davi", "Salomão", "Acabe"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Quem construiu o primeiro Templo de Jerusalém?", opcoes: ["Davi", "Salomão", "Ezequias", "Josias"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Qual rei pediu sabedoria a Deus em vez de riquezas?", opcoes: ["Salomão", "Davi", "Saul", "Roboão"], respostaCorreta: 0, nivel: 'facil', mes: 3 },
    { pergunta: "Quem era o profeta que ungiu tanto Saul quanto Davi como reis?", opcoes: ["Elias", "Samuel", "Natã", "Eliseu"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Qual guerreiro era o melhor amigo de Davi e filho de Saul?", opcoes: ["Abner", "Jónatas", "Is-Bosete", "Mefibosete"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Com qual mulher casada o rei Davi pecou, mandando matar o marido dela?", opcoes: ["Abigail", "Bate-Seba", "Mical", "Isaque"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Qual o nome do marido de Bate-Seba que foi morto por ordem de Davi?", opcoes: ["Urias", "Joabe", "Natã", "Zadoque"], respostaCorreta: 0, nivel: 'facil', mes: 3 },
    { pergunta: "Qual o nome do filho de Davi que se revoltou e tentou tomar o trono?", opcoes: ["Salomão", "Absalão", "Amnon", "Adonias"], respostaCorreta: 1, nivel: 'facil', mes: 3 },
    { pergunta: "Quantos livros de Salmos existem na Bíblia?", opcoes: ["100", "150", "66", "39"], respostaCorreta: 1, nivel: 'facil', mes: 3 },

    { pergunta: "Qual o nome do comandante do exército de Davi?", opcoes: ["Abner", "Joabe", "Amasa", "Benaia"], respostaCorreta: 1, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o nome do filho coxo de Jónatas que Davi acolheu em sua mesa?", opcoes: ["Mefibosete", "Is-Bosete", "Áquis", "Meús"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Onde o rei Saul foi consultar uma médium antes de uma batalha?", opcoes: ["Endor", "Nobe", "Ramá", "Gilgal"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o nome do profeta que confrontou Davi com a parábola da ovelhinha?", opcoes: ["Natã", "Gade", "Samuel", "Aías"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o nome da cidade que se tornou a capital de Israel e cidade de Davi?", opcoes: ["Jerusalém", "Hebrom", "Samaria", "Jericó"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Quantas esposas e concubinas a Bíblia relata que o rei Salomão teve?", opcoes: ["700 esposas e 300 concubinas", "100 esposas e 100 concubinas", "12 esposas", "Apenas uma"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Quem era a mãe do rei Salomão?", opcoes: ["Mical", "Bate-Seba", "Abigail", "Ester"], respostaCorreta: 1, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o nome do monte onde o Templo de Salomão foi construído?", opcoes: ["Monte Moriá", "Monte Sião", "Monte das Oliveiras", "Monte Sinai"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o nome do general de Saul que depois passou o reino para Is-Bosete?", opcoes: ["Abner", "Joabe", "Amasa", "Zadoque"], respostaCorreta: 0, nivel: 'medio', mes: 3 },
    { pergunta: "Qual o livro da Bíblia que contém provérbios majoritariamente escritos por Salomão?", opcoes: ["Provérbios", "Eclesiastes", "Cantares", "Jó"], respostaCorreta: 0, nivel: 'medio', mes: 3 },

    { pergunta: "Qual o nome do sacerdote que traiu Davi apoiando a revolta de Adonias?", opcoes: ["Abiatar", "Zadoque", "Eli", "Aimeleque"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o nome do homem que amaldiçoou e jogou pedras em Davi durante a fuga?", opcoes: ["Simei", "Nabal", "Ziba", "Agague"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o nome do servo de Mefibosete que enganou Davi para ganhar terras?", opcoes: ["Ziba", "Itai", "Huxai", "Barzilai"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o valente de Davi que matou um leão dentro de uma cova num dia de neve?", opcoes: ["Benaia", "Josebe-Bassebete", "Elazar", "Abisai"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Quantos anos durou o reinado de Davi ao todo?", opcoes: ["40 anos", "33 anos", "7 anos", "50 anos"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual a cidade onde Davi reinou por 7 anos e meio antes de tomar Jerusalém?", opcoes: ["Hebrom", "Belém", "Gibeom", "Ramá"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o profeta que rasgou sua capa em 12 pedaços para dar 10 a Jeroboão?", opcoes: ["Aías de Siló", "Semaias", "Jeú", "Micaías"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o rei de Tiro que enviou materiais para a construção do palácio de Davi?", opcoes: ["Hiram", "Etbaal", "Zacarias", "Aquis"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o nome do primeiro filho que Bate-Seba teve com Davi (que faleceu)?", opcoes: ["Filho sem nome citado especificamente na Bíblia", "Natan", "Shammua", "Ibhar"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },
    { pergunta: "Qual o monte onde o rei Saul e seus filhos morreram na batalha contra os filisteus?", opcoes: ["Monte Gilboa", "Monte Carmelo", "Monte Tabor", "Monte Ebal"], respostaCorreta: 0, nivel: 'dificil', mes: 3 },


    

    { pergunta: "Qual o nome do profeta que foi levado ao céu em uma carruagem de fogo?", opcoes: ["Eliseu", "Elias", "Isaías", "Jeremias"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Quem foi o sucessor de Elias que pediu porção dobrada do seu espírito?", opcoes: ["Isaías", "Eliseu", "Geazi", "Amós"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Qual o nome da rainha má de Israel que adorava a Baal e foi comida pelos cães?", opcoes: ["Vasti", "Jezabel", "Atalia", "Ester"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Qual o nome do capitão sírio leproso que foi curado no rio Jordão?", opcoes: ["Naamã", "Hazael", "Ben-Hadade", "Sin"], respostaCorreta: 0, nivel: 'facil', mes: 4 },
    { pergunta: "Qual o profeta que engoliu um rolo de livro dado por Deus?", opcoes: ["Ezequiel", "Jeremias", "Daniel", "Isaías"], respostaCorreta: 0, nivel: 'facil', mes: 4 },
    { pergunta: "Qual rei de Judá teve sua vida prolongada por 15 anos após orar chorando?", opcoes: ["Josias", "Ezequias", "Acaz", "Manassés"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Qual profeta interpretou a escrita na parede durante a festa de Belsazar?", opcoes: ["Jeremias", "Ezequiel", "Daniel", "Isaías"], respostaCorreta: 2, nivel: 'facil', mes: 4 },
    { pergunta: "Qual rainha judia salvou seu povo do extermínio na Pérsia?", opcoes: ["Rute", "Ester", "Débora", "Noemi"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Quem liderou a reconstrução dos muros de Jerusalém após o exílio?", opcoes: ["Esdras", "Neemias", "Zorobabel", "Ageu"], respostaCorreta: 1, nivel: 'facil', mes: 4 },
    { pergunta: "Quem liderou o retorno dos judeus para reconstruir o Templo?", opcoes: ["Neemias", "Esdras", "Zorobabel", "Mardoqueu"], respostaCorreta: 2, nivel: 'facil', mes: 4 },

    { pergunta: "Qual profeta profetizou que o Messias nasceria de uma virgem (Emanuel)?", opcoes: ["Jeremias", "Isaías", "Ezequiel", "Daniel"], respostaCorreta: 1, nivel: 'medio', mes: 4 },
    { pergunta: "Qual o nome do rei persa que era esposo da rainha Ester?", opcoes: ["Ciro", "Dario", "Assuero (Xerxes)", "Artaxerxes"], respostaCorreta: 2, nivel: 'medio', mes: 4 },
    { pergunta: "Quem era o primo de Ester que se recusou a se curvar a Hamã?", opcoes: ["Mardoqueu", "Hagai", "Esdras", "Neemias"], respostaCorreta: 0, nivel: 'medio', mes: 4 },
    { pergunta: "Quem planejou destruir os judeus e foi enforcado na sua própria forca?", opcoes: ["Sanbalat", "Tobias", "Hamã", "Belsazar"], respostaCorreta: 2, nivel: 'medio', mes: 4 },
    { pergunta: "Qual profeta foi lançado na cova dos leões por orar a Deus?", opcoes: ["Jeremias", "Daniel", "Amós", "Jonas"], respostaCorreta: 1, nivel: 'medio', mes: 4 },
    { pergunta: "Qual o nome dos três amigos de Daniel jogados na fornalha ardente?", opcoes: ["Sadraque, Mesaque e Abede-Nego", "Pedro, Tiago e João", "Moisés, Aarão e Hur", "Esdras, Neemias e Zorobabel"], respostaCorreta: 0, nivel: 'medio', mes: 4 },
    { pergunta: "Qual profeta se casou com uma mulher chamada Gômer?", opcoes: ["Oseias", "Joel", "Amós", "Jonas"], respostaCorreta: 0, nivel: 'medio', mes: 4 },
    { pergunta: "Qual profeta era um boiadeiro antes de ser chamado por Deus?", opcoes: ["Amós", "Miqueias", "Naum", "Sofonias"], respostaCorreta: 0, nivel: 'medio', mes: 4 },
    { pergunta: "Qual o menor livro do Antigo Testamento?", opcoes: ["Jonas", "Obadias", "Naum", "Ageu"], respostaCorreta: 1, nivel: 'medio', mes: 4 },
    { pergunta: "Qual profeta fugiu de sua missão e foi engolido por um grande peixe?", opcoes: ["Nahum", "Jonas", "Habacuque", "Malaquias"], respostaCorreta: 1, nivel: 'medio', mes: 4 },

    { pergunta: "Qual o rei da Babilônia que destruiu o Templo de Jerusalém em 586 a.C.?", opcoes: ["Ciro", "Nabucodonosor", "Dario", "Belsazar"], respostaCorreta: 1, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual o rio na Babilônia onde Daniel teve a visão dos animais?", opcoes: ["Rio Ulai", "Rio Quebar", "Rio Tigre", "Rio Eufrates"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual o escriba e sacerdote que ensinou a lei ao povo após o cativeiro?", opcoes: ["Esdras", "Neemias", "Zorobabel", "Josué"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Quem tentou impedir Neemias de reconstruir os muros?", opcoes: ["Sanbalat", "Gesém", "Tobias", "Todos os anteriores juntos"], respostaCorreta: 3, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual profeta questionou a Deus por que os ímpios prosperavam?", opcoes: ["Habacuque", "Sofonias", "Miqueias", "Ageu"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual profeta incentivou Zorobabel a reconstruir o templo dizendo que a glória seria maior?", opcoes: ["Ageu", "Zacarias", "Malaquias", "Obadias"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual profeta encerra o Antigo Testamento falando da vinda de Elias?", opcoes: ["Malaquias", "Zacarias", "Ageu", "Daniel"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual rei persa decretou fundos para a reconstrução do templo liderada por Esdras?", opcoes: ["Artaxerxes", "Ciro", "Dario", "Xerxes"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual a visão de Ezequiel onde ossos secos ganham vida?", opcoes: ["Vale dos Ossos Secos", "Carruagem de Fogo", "Templo Celestial", "Rolo Voador"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },
    { pergunta: "Qual profeta profetizou que o Messias viria montado em um jumentinho?", opcoes: ["Zacarias", "Isaías", "Jeremias", "Amós"], respostaCorreta: 0, nivel: 'dificil', mes: 4 },


    

    { pergunta: "Em qual cidade Jesus nasceu?", opcoes: ["Nazaré", "Belém", "Jerusalém", "Cafarnaum"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Quem foi a mãe terrena de Jesus?", opcoes: ["Isabel", "Maria", "Marta", "Magdalena"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Quem batizou Jesus no rio Jordão?", opcoes: ["Pedro", "João Batista", "Paulo", "Tiago"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Em qual localidade aconteceu o primeiro milagre de transformar água em vinho?", opcoes: ["Caná da Galileia", "Jerusalém", "Jericó", "Nazaré"], respostaCorreta: 0, nivel: 'facil', mes: 5 },
    { pergunta: "Quantos discípulos principais Jesus escolheu?", opcoes: ["7", "10", "12", "70"], respostaCorreta: 2, nivel: 'facil', mes: 5 },
    { pergunta: "Qual apóstolo andou sobre as águas por um instante ao olhar para Jesus?", opcoes: ["João", "Pedro", "André", "Filipe"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Quem traiu Jesus por 30 moedas de prata?", opcoes: ["Tomé", "Judas Iscariotes", "Pedro", "Pilatos"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Em que dia da semana Jesus ressuscitou?", opcoes: ["Sábado", "Domingo (Primeiro dia)", "Sexta-feira", "Quinta-feira"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Quantos evangelhos existem no Novo Testamento?", opcoes: ["2", "4", "7", "12"], respostaCorreta: 1, nivel: 'facil', mes: 5 },
    { pergunta: "Quem escreveu a maioria das epístolas do Novo Testamento?", opcoes: ["Pedro", "João", "Paulo", "Tiago"], respostaCorreta: 2, nivel: 'facil', mes: 5 },

    { pergunta: "Qual evangelho começa dizendo: 'No princípio era o Verbo...'?", opcoes: ["Mateus", "Marcos", "Lucas", "João"], respostaCorreta: 3, nivel: 'medio', mes: 5 },
    { pergunta: "Qual monte foi o cenário da transfiguração de Jesus?", opcoes: ["Monte Tabor", "Monte Sinai", "Monte das Oliveiras", "Gólgota"], respostaCorreta: 0, nivel: 'medio', mes: 5 },
    { pergunta: "Qual fariseu visitou Jesus à noite para conversar sobre o novo nascimento?", opcoes: ["Zaqueu", "Nicodemos", "Gamaliel", "Caifás"], respostaCorreta: 1, nivel: 'medio', mes: 5 },
    { pergunta: "Em qual cidade Jesus ressuscitou Lázaro?", opcoes: ["Nazaré", "Betânia", "Cafarnaum", "Jerusalém"], respostaCorreta: 1, nivel: 'medio', mes: 5 },
    { pergunta: "Qual o nome do cego que clamou por misericórdia perto de Jericó?", opcoes: ["Bartimeu", "Zaqueu", "Malco", "Eteco"], respostaCorreta: 0, nivel: 'medio', mes: 5 },
    { pergunta: "Qual era a profissão de Mateus antes de seguir a Jesus?", opcoes: ["Pescador", "Cobrador de impostos", "Médico", "Carpinteiro"], respostaCorreta: 1, nivel: 'medio', mes: 5 },
    { pergunta: "Qual apóstolo era médico?", opcoes: ["Lucas", "Marcos", "Paulo", "Timóteo"], respostaCorreta: 0, nivel: 'medio', mes: 5 },
    { pergunta: "Qual festa judaica ocorria quando o Espírito Santo foi derramado em Atos 2?", opcoes: ["Páscoa", "Pentecostes", "Tabernáculos", "Yom Kippur"], respostaCorreta: 1, nivel: 'medio', mes: 5 },
    { pergunta: "Quem foi o primeiro mártir cristão apedrejado?", opcoes: ["Estêvão", "Tiago", "Antipas", "Marcos"], respostaCorreta: 0, nivel: 'medio', mes: 5 },
    { pergunta: "Qual o nome do centurião romano que foi o primeiro gentio convertido em Cesareia?", opcoes: ["Cornélio", "Júlio", "Sérgio Paulo", "Lúcio"], respostaCorreta: 0, nivel: 'medio', mes: 5 },

    { pergunta: "Quais sumos sacerdotes presidiram o julgamento de Jesus?", opcoes: ["Anas e Caifás", "Gamaliel", "Hileil", "Shammai"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual o nome do 'Campo de Sangue' comprado com o dinheiro de Judas?", opcoes: ["Aceldama", "Golgota", "Gabata", "Cédrom"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual o nome do prisioneiro solto pela multidão no lugar de Jesus?", opcoes: ["Barrabás", "Dimas", "Gesta", "Malco"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual o nome do servo do sumo sacerdote que teve a orelha cortada por Pedro?", opcoes: ["Malco", "Anas", "Simeão", "Zacarias"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Em qual monte Jesus ascendeu ao céu?", opcoes: ["Monte das Oliveiras", "Monte Sinai", "Monte Sião", "Monte Moriá"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Quem substituiu Judas Iscariotes no grupo dos apóstolos?", opcoes: ["Matias", "Barnabé", "Justo", "Silas"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual casal mentiu sobre o valor de uma venda e morreu diante de Pedro?", opcoes: ["Ananias e Safira", "Áquila e Priscila", "Félix e Drusila", "Herodes e Herodias"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual mestre da lei defendeu os apóstolos no Sinédrio?", opcoes: ["Gamaliel", "Nicodemos", "Anas", "Caifás"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Quem tentou comprar o poder do Espírito Santo em Samaria?", opcoes: ["Simão o Mago", "Elimas", "Bar-Jesus", "Janes"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },
    { pergunta: "Qual o nome do eunuco etíope evangelizado por Filipe?", opcoes: ["Não tem nome próprio citado", "Candace", "Ebed-Meleque", "Simeão"], respostaCorreta: 0, nivel: 'dificil', mes: 5 },


    
    
    { pergunta: "Quem escreveu o livro de Apocalipse?", opcoes: ["Paulo", "Pedro", "João", "Tiago"], respostaCorreta: 2, nivel: 'facil', mes: 6 },
    { pergunta: "Em qual ilha João recebeu as visões do Apocalipse?", opcoes: ["Creta", "Patmos", "Chipre", "Malta"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "Qual apóstolo antes perseguia a igreja e depois escreveu várias cartas?", opcoes: ["Pedro", "João", "Paulo", "Barnabé"], respostaCorreta: 2, nivel: 'facil', mes: 6 },
    { pergunta: "Qual o nome do casal de fabricantes de tendas que ajudou Paulo?", opcoes: ["Ananias e Safira", "Áquila e Priscila", "Félix e Drusila", "Zacarias e Isabel"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "Qual livro do Novo Testamento vem logo após os Evangelhos?", opcoes: ["Romanos", "Atos dos Apóstolos", "Apocalipse", "Gálatas"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "Quem foi o jovem discípulo que recebeu duas cartas pessoais de Paulo?", opcoes: ["Tito", "Timóteo", "Lucas", "Marcos"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "O que significa a palavra 'Evangelho'?", opcoes: ["Boa Notícia", "História Antiga", "Lei de Deus", "Fim dos Tempos"], respostaCorreta: 0, nivel: 'facil', mes: 6 },
    { pergunta: "Em qual cidade Paulo e Silas cantaram na prisão antes do terremoto?", opcoes: ["Roma", "Filipos", "Corinto", "Éfeso"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "Qual apóstolo negou Jesus três vezes?", opcoes: ["João", "Pedro", "Tomé", "André"], respostaCorreta: 1, nivel: 'facil', mes: 6 },
    { pergunta: "Quem subiu em uma árvore para ver Jesus passar em Jericó?", opcoes: ["Zaqueu", "Nicodemos", "Lázaro", "Bartimeu"], respostaCorreta: 0, nivel: 'facil', mes: 6 },

    { pergunta: "Quantas igrejas da Ásia recebem cartas no Apocalipse?", opcoes: ["5", "7", "12", "10"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Qual o nome do escravo por quem Paulo intercedeu na carta a Filemom?", opcoes: ["Onésimo", "Tíquico", "Erasto", "Aristarco"], respostaCorreta: 0, nivel: 'medio', mes: 6 },
    { pergunta: "Quem escreveu a carta aos Romanos?", opcoes: ["Pedro", "João", "Paulo", "Tiago"], respostaCorreta: 2, nivel: 'medio', mes: 6 },
    { pergunta: "Onde os seguidores de Cristo foram chamados de 'cristãos' pela primeira vez?", opcoes: ["Jerusalém", "Antioquia", "Roma", "Damasco"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Quem caiu da janela enquanto Paulo pregava e foi ressuscitado?", opcoes: ["Êutico", "Áquila", "Timóteo", "Trófimo"], respostaCorreta: 0, nivel: 'medio', mes: 6 },
    { pergunta: "Qual governador romano tremeu ao ouvir Paulo falar sobre o juízo?", opcoes: ["Pilatos", "Félix", "Festo", "Sérgio Paulo"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Qual rei disse a Paulo: 'Por pouco me persuades a fazer-me cristão'?", opcoes: ["Herodes Agripa I", "Herodes Agripa II", "César Augusto", "Tibério César"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Qual carta de Paulo foca fortemente na alegria na prisão?", opcoes: ["Gálatas", "Filipenses", "Efésios", "Colossenses"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Onde está escrita a famosa descrição do amor ('O amor é paciente...')?", opcoes: ["Romanos", "1 Coríntios 13", "Efésios", "Tiago"], respostaCorreta: 1, nivel: 'medio', mes: 6 },
    { pergunta: "Qual o nome da vendedora de púrpura convertida em Filipos?", opcoes: ["Lídia", "Priscila", "Drusila", "Dâmaris"], respostaCorreta: 0, nivel: 'medio', mes: 6 },

    { pergunta: "Qual o nome do falso profeta em Pafos cegado por Paulo?", opcoes: ["Bar-Jesus (Elimas)", "Simão", "Alexander", "Himeneu"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Qual o grande tema defendido por Paulo em Gálatas?", opcoes: ["A salvação pela graça mediante a fé", "A guarda do sábado", "A profecia do fim", "A estrutura da igreja"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Qual o médico que acompanhou Paulo e escreveu um Evangelho?", opcoes: ["Lucas", "Marcos", "Justo", "Demas"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Quem hospedou Paulo em Malta após o naufrágio?", opcoes: ["Públio", "Júlio", "Publius", "Estefanas"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Quem foram os dois opositores de Moisés citados por Paulo em 2 Timóteo?", opcoes: ["Janes e Jambres", "Himeneu e Fileto", "Alexander e Himeneu", "Demas e Diótrefes"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Qual cooperador abandonou Paulo por amar o presente século?", opcoes: ["Demas", "Lucas", "Tiquico", "Marcos"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Quem Paulo deixou em Creta para organizar a igreja?", opcoes: ["Tito", "Timóteo", "Tiquico", "Filemom"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Qual o capítulo de Hebreus conhecido como a galeria da fé?", opcoes: ["Capítulo 11", "Capítulo 3", "Capítulo 8", "Capítulo 13"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Quem é apontado em Hebreus como sacerdote eterno segundo Melquisedeque?", opcoes: ["Jesus Cristo", "Abraão", "Aarão", "Moisés"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },
    { pergunta: "Qual líder tirano amava ter a primazia na igreja segundo 3 João?", opcoes: ["Diótrefes", "Demas", "Alexander", "Diotrephes"], respostaCorreta: 0, nivel: 'dificil', mes: 6 },


    

    { pergunta: "Quem foi o homem mais paciente da Bíblia?", opcoes: ["Moisés", "Jó", "Abraão", "Davi"], respostaCorreta: 1, nivel: 'facil', mes: 7 },
    { pergunta: "O que Jó perdeu primeiro em sua provação?", opcoes: ["Seus filhos e seus bens", "Sua saúde física", "A paciência", "Sua esposa"], respostaCorreta: 0, nivel: 'facil', mes: 7 },
    { pergunta: "Quantos amigos vieram consolar Jó no início?", opcoes: ["3 amigos principais", "12 amigos", "7 amigos", "Nenhum amigo"], respostaCorreta: 0, nivel: 'facil', mes: 7 },
    { pergunta: "Qual o livro poético composto por cânticos e orações (maioria de Davi)?", opcoes: ["Provérbios", "Salmos", "Eclesiastes", "Cantares"], respostaCorreta: 1, nivel: 'facil', mes: 7 },
    { pergunta: "Quem escreveu Eclesiastes ('Vaidade de vaidades...')?", opcoes: ["Davi", "Salomão", "Jó", "Moisés"], respostaCorreta: 1, nivel: 'facil', mes: 7 },
    { pergunta: "Qual o livro que celebra o amor romântico?", opcoes: ["Cantares de Salomão", "Rute", "Ester", "Provérbios"], respostaCorreta: 0, nivel: 'facil', mes: 7 },
    { pergunta: "Qual o objetivo principal do livro de Provérbios?", opcoes: ["Ensinar sabedoria prática e temor do Senhor", "Contar a história de Israel", "Falar sobre o fim do mundo", "Trazer leis civis"], respostaCorreta: 0, nivel: 'facil', mes: 7 },
    { pergunta: "Quem é comparado a uma árvore junto a ribeiros de águas no Salmo 1?", opcoes: ["O ímpio", "O justo", "O rei", "O profeta"], respostaCorreta: 1, nivel: 'facil', mes: 7 },
    { pergunta: "Qual o salmo que começa com 'O Senhor é o meu pastor; nada me faltará'?", opcoes: ["Salmo 23", "Salmo 91", "Salmo 121", "Salmo 51"], respostaCorreta: 0, nivel: 'facil', mes: 7 },
    { pergunta: "Qual o salmo de arrependimento escrito por Davi após pecar com Bate-Seba?", opcoes: ["Salmo 51", "Salmo 23", "Salmo 1", "Salmo 100"], respostaCorreta: 0, nivel: 'facil', mes: 7 },

    { pergunta: "Qual o nome do amigo mais jovem de Jó que falou por último?", opcoes: ["Elifaz", "Bildade", "Zofar", "Eliú"], respostaCorreta: 3, nivel: 'medio', mes: 7 },
    { pergunta: "De onde o Senhor respondeu a Jó no final?", opcoes: ["De um redemoinho", "De uma sarça ardente", "De um sonho", "Do alto de um monte"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "O que aconteceu com os bens de Jó no final de sua história?", opcoes: ["Deus lhe deu tudo em dobro", "Ele continuou pobre", "Recuperou apenas os filhos", "Nada mudou"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "O temor do Senhor é o princípio de quê, segundo Provérbios?", opcoes: ["Da sabedoria", "Da riqueza", "Da paz", "Da vida longa"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "Segundo Eclesiastes, há tempo de nascer e tempo de...?", opcoes: ["Morrer", "Crescer", "Trabalhar", "Chorar apenas"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "Quais os nomes dos três primeiros amigos que acusaram Jó?", opcoes: ["Elifaz, Bildade e Zofar", "Sadraque, Mesaque e Abede-Nego", "Pedro, Tiago e João", "Anas, Caifás e Gamaliel"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "Quem provocou as desgraças e feridas na vida de Jó?", opcoes: ["Satanás (com permissão de Deus)", "Os caldeus", "Os sabeus", "Deus diretamente"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "Qual o salmo que pede um coração puro ('Cria em mim, ó Deus...')?", opcoes: ["Salmo 51", "Salmo 23", "Salmo 32", "Salmo 139"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "Qual salmo detalha a onipresença de Deus ('Para onde me ausentarei...')?", opcoes: ["Salmo 139", "Salmo 91", "Salmo 8", "Salmo 19"], respostaCorreta: 0, nivel: 'medio', mes: 7 },
    { pergunta: "O que Provérbios diz para não fazermos com o nosso próprio entendimento?", opcoes: ["Não te estribues nele", "Não o compartilhes", "Não o siga", "Não o valorize"], respostaCorreta: 0, nivel: 'medio', mes: 7 },

    { pergunta: "Qual a terra de origem de Jó?", opcoes: ["Terra de Uz", "Terra de Midiã", "Terra de Canaã", "Terra de Ur"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Quais os dois grandes animais descritos a Jó no final para mostrar a soberania de Deus?", opcoes: ["Beemote e Leviatã", "Leão e Urso", "Elefante e Crocodilo", "Águia e Touro"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Quantos anos a mais Jó viveu após sua restauração?", opcoes: ["140 anos", "70 anos", "100 anos", "120 anos"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Qual o nome das três filhas de Jó após sua restauração?", opcoes: ["Jemima, Quézia e Querém-Hapuque", "Sara, Raquel e Lia", "Ester, Rute e Débora", "Orfa, Noemi e Ada"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Segundo Provérbios 30, quais são as quatro pequenas coisas extremamente sábias?", opcoes: ["Formiga, coelho, gafanhotos e lagartixa", "Leão, urso, leopardo e águia", "Abelha, aranha, formiga e borboleta", "Cão, gato, boi e jumento"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "O que deve ser guardado acima de tudo, segundo Provérbios 4?", opcoes: ["O coração", "Os pensamentos", "As riquezas", "Os sentimentos"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Qual a conclusão final do pregador no livro de Eclesiastes?", opcoes: ["Teme a Deus e guarda os Seus mandamentos", "Busca a sabedoria", "Aproveita o momento", "O conhecimento traz tristeza"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Qual o salmo que é uma oração de Moisés ('Senhor, tu tens sido o nosso refúgio')?", opcoes: ["Salmo 90", "Salmo 23", "Salmo 119", "Salmo 84"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Qual o maior salmo da Bíblia (focado na Palavra)?", opcoes: ["Salmo 119", "Salmo 78", "Salmo 89", "Salmo 106"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },
    { pergunta: "Como são chamados os salmos do 120 ao 134?", opcoes: ["Cânticos de Degraus (Subidas)", "Salmos Aleluia", "Salmos Messiânicos", "Salmos de Correção"], respostaCorreta: 0, nivel: 'dificil', mes: 7 },


    
    
    { pergunta: "Quem construiu a arca para escapar do dilúvio?", opcoes: ["Moisés", "Abraão", "Noé", "Davi"], respostaCorreta: 2, nivel: 'facil', mes: 8 },
    { pergunta: "Qual é o primeiro livro da Bíblia?", opcoes: ["Êxodo", "Gênesis", "Levítico", "Mateus"], respostaCorreta: 1, nivel: 'facil', mes: 8 },
    { pergunta: "Quem derrotou o gigante Golias com uma funda e pedras?", opcoes: ["Sansão", "Saul", "Salomão", "Davi"], respostaCorreta: 3, nivel: 'facil', mes: 8 },
    { pergunta: "Quem foi engolido por um grande peixe após desobedecer a Deus?", opcoes: ["Pedro", "Jonas", "João", "Paulo"], respostaCorreta: 1, nivel: 'facil', mes: 8 },
    { pergunta: "Quantos mandamentos Deus entregou a Moisés no Monte Sinai?", opcoes: ["7", "10", "12", "40"], respostaCorreta: 1, nivel: 'facil', mes: 8 },
    { pergunta: "Qual era o nome do primeiro homem criado por Deus?", opcoes: ["Abel", "Adão", "Set", "Noé"], respostaCorreta: 1, nivel: 'facil', mes: 8 },
    { pergunta: "Quem foi vendido pelos irmãos e se tornou governador no Egito?", opcoes: ["José", "Benjamin", "Ruben", "Judá"], respostaCorreta: 0, nivel: 'facil', mes: 8 },
    { pergunta: "Qual o nome da esposa de Adão?", opcoes: ["Sara", "Rebeca", "Eva", "Raquel"], respostaCorreta: 2, nivel: 'facil', mes: 8 },
    { pergunta: "Em qual cidade Jesus nasceu?", opcoes: ["Nazaré", "Jerusalém", "Belém", "Cafarnaum"], respostaCorreta: 2, nivel: 'facil', mes: 8 },
    { pergunta: "Quantos discípulos principais Jesus escolheu?", opcoes: ["7", "10", "12", "70"], respostaCorreta: 2, nivel: 'facil', mes: 8 },

    { pergunta: "Qual foi o primeiro milagre de Jesus registrado na Bíblia?", opcoes: ["Cura de um cego", "Transformar água em vinho", "Multiplicação dos pães", "Andar sobre as águas"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Qual apóstolo negou Jesus três vezes antes de o galo cantar?", opcoes: ["João", "Tiago", "Pedro", "André"], respostaCorreta: 2, nivel: 'medio', mes: 8 },
    { pergunta: "Qual era o nome da esposa de Abraão?", opcoes: ["Rute", "Sara", "Rebeca", "Raquel"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Quantos dias Jesus passou jejuando no deserto?", opcoes: ["7 dias", "12 dias", "30 dias", "40 dias"], respostaCorreta: 3, nivel: 'medio', mes: 8 },
    { pergunta: "Qual profeta interpretou os sonhos do Faraó sobre as vacas gordas e magras?", opcoes: ["Daniel", "José", "Moisés", "Elias"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Quem foi o sucessor de Moisés na liderança do povo de Israel?", opcoes: ["Calebe", "Josué", "Arão", "Samuel"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Qual rainha salvou o seu povo da destruição na Pérsia?", opcoes: ["Vasti", "Ester", "Rute", "Débora"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Em qual monte Moisés recebeu as tábuas da lei?", opcoes: ["Monte das Oliveiras", "Monte Sinai", "Monte Carmelo", "Monte Moriah"], respostaCorreta: 1, nivel: 'medio', mes: 8 },
    { pergunta: "Qual era a profissão do apóstolo Mateus antes de seguir a Jesus?", opcoes: ["Pescador", "Carpinteiro", "Cobrador de impostos", "Médico"], respostaCorreta: 2, nivel: 'medio', mes: 8 },
    { pergunta: "Quem subiu em um sicômoro para conseguir ver Jesus passar?", opcoes: ["Zaqueu", "Nicodemos", "Bartimeu", "Lázaro"], respostaCorreta: 0, nivel: 'medio', mes: 8 },

    { pergunta: "Qual profeta foi levado ao céu em uma carruagem de fogo?", opcoes: ["Eliseu", "Elias", "Isaías", "Ezequiel"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual o nome do vale onde ocorreu a batalha final mencionada no Apocalipse?", opcoes: ["Megido (Armagedom)", "Cedrom", "Eshcol", "Sin"], respostaCorreta: 0, nivel: 'dificil', mes: 8 },
    { pergunta: "Quantos anos durou o cativeiro do povo de Israel na Babilônia?", opcoes: ["40 anos", "70 anos", "400 anos", "430 anos"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual o nome do sumo sacerdote que interrogou Jesus antes de enviá-lo a Pilatos?", opcoes: ["Anas", "Caifás", "Gamaliel", "Zacarias"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Na visão de Ezequiel, o que representavam os ossos secos que voltaram à vida?", opcoes: ["A casa de Israel", "Os anjos caídos", "Os reis de Judá", "Os profetas antigos"], respostaCorreta: 0, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual foi o rei de Salém e sacerdote do Deus Altíssimo que abençoou Abraão?", opcoes: ["Abimeleque", "Melquisedeque", "Jetro", "Naamã"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual o monte onde Elias desafiou os profetas de Baal?", opcoes: ["Monte Sinai", "Monte Carmelo", "Monte Nebo", "Monte Tabor"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Quantos capítulos tem o livro de Obadias, o menor do Antigo Testamento?", opcoes: ["1 capítulo", "3 capítulos", "5 capítulos", "2 capítulos"], respostaCorreta: 0, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual o rio no qual o capitão sírio Naamã mergulhou sete vezes para ser curado?", opcoes: ["Rio Nilo", "Rio Jordão", "Rio Eufrates", "Rio Tigre"], respostaCorreta: 1, nivel: 'dificil', mes: 8 },
    { pergunta: "Qual era o nome do monte onde Moisés morreu sem entrar na Terra Prometida?", opcoes: ["Monte Nebo", "Monte Horebe", "Monte Sião", "Monte Gilboa"], respostaCorreta: 0, nivel: 'dificil', mes: 8 },


    

    { pergunta: "Quem foi lançado na cova dos leões?", opcoes: ["Moisés", "Daniel", "Abraão", "Noé"], respostaCorreta: 1, nivel: 'facil', mes: 9 },
    { pergunta: "Quantos dias Jesus ficou jejuando no deserto?", opcoes: ["7 dias", "12 dias", "30 dias", "40 dias"], respostaCorreta: 3, nivel: 'facil', mes: 9 },
    { pergunta: "Qual é o menor livro do Antigo Testamento?", opcoes: ["Obadias", "Miqueias", "Naum", "Ageu"], respostaCorreta: 0, nivel: 'facil', mes: 9 },
    { pergunta: "Quem foi a mãe do profeta Samuel?", opcoes: ["Sara", "Ana", "Rute", "Ester"], respostaCorreta: 1, nivel: 'facil', mes: 9 },
    { pergunta: "Qual rei pediu sabedoria a Deus em vez de riquezas?", opcoes: ["Davi", "Saul", "Salomão", "Josias"], respostaCorreta: 2, nivel: 'facil', mes: 9 },
    { pergunta: "Quem traiu Jesus por 30 moedas de prata?", opcoes: ["Pedro", "Judas Iscariotes", "Tomé", "Pilatos"], respostaCorreta: 1, nivel: 'facil', mes: 9 },
    { pergunta: "Em que rio Jesus foi batizado por João Batista?", opcoes: ["Rio Nilo", "Rio Tigre", "Rio Eufrates", "Rio Jordão"], respostaCorreta: 3, nivel: 'facil', mes: 9 },
    { pergunta: "Qual o nome do monte onde Jesus foi crucificado?", opcoes: ["Monte Sinai", "Gólgota (Calvário)", "Monte Carmelo", "Monte das Oliveiras"], respostaCorreta: 1, nivel: 'facil', mes: 9 },
    { pergunta: "Quem subiu em uma figueira brava (sicômoro) para ver Jesus?", opcoes: ["Zaqueu", "Nicodemos", "Lázaro", "Bartimeu"], respostaCorreta: 0, nivel: 'facil', mes: 9 },
    { pergunta: "Quem escreveu o livro do Apocalipse?", opcoes: ["Paulo", "Pedro", "João", "Tiago"], respostaCorreta: 2, nivel: 'facil', mes: 9 },

    { pergunta: "Qual era o nome do monte onde Abraão quase sacrificou Isaque?", opcoes: ["Monte Moriá", "Monte Sinai", "Monte Nebo", "Monte Carmelo"], respostaCorreta: 0, nivel: 'medio', mes: 9 },
    { pergunta: "Quem foi o profeta que sucedeu a Elias?", opcoes: ["Isaías", "Jeremias", "Eliseu", "Ezequiel"], respostaCorreta: 2, nivel: 'medio', mes: 9 },
    { pergunta: "Qual o nome da sogra de Rute?", opcoes: ["Orfa", "Noemi", "Ester", "Vasti"], respostaCorreta: 1, nivel: 'medio', mes: 9 },
    { pergunta: "Quantas pragas Deus enviou sobre o Egito?", opcoes: ["7 pragas", "10 pragas", "12 pragas", "40 pragas"], respostaCorreta: 1, nivel: 'medio', mes: 9 },
    { pergunta: "Qual apóstolo era médico?", opcoes: ["Pedro", "João", "Lucas", "Mateus"], respostaCorreta: 2, nivel: 'medio', mes: 9 },
    { pergunta: "Qual o nome do jardim onde Jesus orou antes de ser preso?", opcoes: ["Éden", "Getsêmani", "Getis", "Hesrom"], respostaCorreta: 1, nivel: 'medio', mes: 9 },
    { pergunta: "Quem confrontou os profetas de Baal no Monte Carmelo?", opcoes: ["Elias", "Moisés", "Samuel", "Gideão"], respostaCorreta: 0, nivel: 'medio', mes: 9 },
    { pergunta: "Qual o nome do sumo sacerdote que interrogou Jesus e rasgou suas vestes?", opcoes: ["Anas", "Caifás", "Gamaliel", "Zacarias"], respostaCorreta: 1, nivel: 'medio', mes: 9 },
    { pergunta: "Quem foi o homem que ajudou Jesus a carregar a cruz?", opcoes: ["José de Arimateia", "Simão Cireneu", "Nicodemos", "Barnabé"], respostaCorreta: 1, nivel: 'medio', mes: 9 },
    { pergunta: "Qual era o nome da cidade onde Lázaro foi ressuscitado?", opcoes: ["Jericó", "Betânia", "Nazaré", "Samaria"], respostaCorreta: 1, nivel: 'medio', mes: 9 },

    { pergunta: "Qual o nome da esposa do rei Acabe que promoveu a adoração a Baal?", opcoes: ["Atalia", "Jezabel", "Vasti", "Maaca"], respostaCorreta: 1, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual profeta escreveu detalhadamente sobre o 'Servo Sofredor' no capítulo 53?", opcoes: ["Jeremias", "Ezequiel", "Isaías", "Daniel"], respostaCorreta: 2, nivel: 'dificil', mes: 9 },
    { pergunta: "Na visão do profeta Zacarias, o que apareceu voando?", opcoes: ["Um rolo voador", "Uma águia de fogo", "Um anjo com espada", "Um cavalo branco"], respostaCorreta: 0, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual o nome do pai do profeta Samuel?", opcoes: ["Elcana", "Eli", "Jessé", "Zadom"], respostaCorreta: 0, nivel: 'dificil', mes: 9 },
    { pergunta: "Quantos capítulos tem o livro do profeta Isaías?", opcoes: ["40 capítulos", "50 capítulos", "66 capítulos", "150 capítulos"], respostaCorreta: 2, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual era o nome do escravo fugitivo que Paulo encontrou e mandou de volta a Filemom?", opcoes: ["Onésimo", "Tíquico", "Áquila", "Erasto"], respostaCorreta: 0, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual profeta foi jogado em uma cisterna lamacenta por causa de suas profecias?", opcoes: ["Amós", "Jeremias", "Miqueias", "Oseias"], respostaCorreta: 1, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual o nome da ilha onde o apóstolo João recebeu a revelação do Apocalipse?", opcoes: ["Creta", "Malta", "Patmos", "Chipre"], respostaCorreta: 2, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual rei persa emitiu o decreto permitindo que os judeus voltassem para reconstruir Jerusalém?", opcoes: ["Dario", "Artaxerxes", "Ciro", "Xerxes"], respostaCorreta: 2, nivel: 'dificil', mes: 9 },
    { pergunta: "Qual o nome do sumo sacerdote contemporâneo de Neemias na reconstrução dos muros?", opcoes: ["Eliasibe", "Joiada", "Hilquias", "Josua"], respostaCorreta: 0, nivel: 'dificil', mes: 9 },


    

    { pergunta: "Quem foi o primeiro rei de Israel?", opcoes: ["Davi", "Saul", "Salomão", "Samuel"], respostaCorreta: 1, nivel: 'facil', mes: 10 },
    { pergunta: "Quem escreveu a maioria das epístolas (cartas) do Novo Testamento?", opcoes: ["Pedro", "João", "Paulo", "Tiago"], respostaCorreta: 2, nivel: 'facil', mes: 10 },
    { pergunta: "Qual o nome da irmã de Moisés?", opcoes: ["Débora", "Miriã", "Raquel", "Abigail"], respostaCorreta: 1, nivel: 'facil', mes: 10 },
    { pergunta: "Quem foi conhecido na Bíblia como o homem mais paciente?", opcoes: ["Jó", "Abraão", "Isaque", "Noé"], respostaCorreta: 0, nivel: 'facil', mes: 10 },
    { pergunta: "Qual cidade teve suas muralhas caídas após o povo rodear e gritar?", opcoes: ["Jerusalém", "Jericó", "Babilônia", "Nínive"], respostaCorreta: 1, nivel: 'facil', mes: 10 },
    { pergunta: "Qual profeta foi engolido por um grande peixe?", opcoes: ["Elias", "Jonas", "Eliseu", "Isaías"], respostaCorreta: 1, nivel: 'facil', mes: 10 },
    { pergunta: "Quem negou Jesus três vezes antes do galo cantar?", opcoes: ["João", "Judas", "Pedro", "André"], respostaCorreta: 2, nivel: 'facil', mes: 10 },
    { pergunta: "Qual o nome do monte onde os Dez Mandamentos foram entregues?", opcoes: ["Monte Sinai", "Monte Carmelo", "Monte das Oliveiras", "Monte Moriá"], respostaCorreta: 0, nivel: 'facil', mes: 10 },
    { pergunta: "Quantos dias durou a criação do mundo segundo o relato de Gênesis?", opcoes: ["3 dias", "6 dias", "7 dias", "40 dias"], respostaCorreta: 1, nivel: 'facil', mes: 10 },
    { pergunta: "Quem foi o sucessor de Moisés na liderança de Israel?", opcoes: ["Calebe", "Josué", "Arão", "Pinhas"], respostaCorreta: 1, nivel: 'facil', mes: 10 },

    { pergunta: "Qual o nome do monte onde Moisés viu a Terra Prometida e faleceu?", opcoes: ["Monte Sinai", "Monte Nebo", "Monte Horebe", "Monte Tabor"], respostaCorreta: 1, nivel: 'medio', mes: 10 },
    { pergunta: "Quem foi o sucessor de Saul no trono de Israel?", opcoes: ["Salomão", "Absalão", "Davi", "Is-Bosete"], respostaCorreta: 2, nivel: 'medio', mes: 10 },
    { pergunta: "Qual o nome do lugar onde o povo tentou construir uma torre para alcançar o céu?", opcoes: ["Babel", "Nínive", "Ur", "Haram"], respostaCorreta: 0, nivel: 'medio', mes: 10 },
    { pergunta: "Quem era o sumo sacerdote quando o menino Samuel ministrava no templo?", opcoes: ["Eli", "Zadoque", "Abiatar", "Anas"], respostaCorreta: 0, nivel: 'medio', mes: 10 },
    { pergunta: "Quem foi a rainha que visitou Salomão para testar sua sabedoria?", opcoes: ["Rainha de Sabá", "Rainha Ester", "Rainha Vasti", "Jezabel"], respostaCorreta: 0, nivel: 'medio', mes: 10 },
    { pergunta: "Qual o nome do apóstolo que substituiu Judas Iscariotes?", opcoes: ["Barnabé", "Paulo", "Matias", "Silas"], respostaCorreta: 2, nivel: 'medio', mes: 10 },
    { pergunta: "Em qual ilha o apóstolo Paulo sofreu um naufrágio a caminho de Roma?", opcoes: ["Creta", "Chipre", "Malta", "Patmos"], respostaCorreta: 2, nivel: 'medio', mes: 10 },
    { pergunta: "Quem era o governador romano que entregou Jesus para ser crucificado?", opcoes: ["Herodes", "Pôncio Pilatos", "Félix", "Festo"], respostaCorreta: 1, nivel: 'medio', mes: 10 },
    { pergunta: "Qual o nome do rio onde Naamã mergulhou para ser curado da lepra?", opcoes: ["Rio Nilo", "Rio Jordão", "Rio Eufrates", "Rio Jaboque"], respostaCorreta: 1, nivel: 'medio', mes: 10 },
    { pergunta: "Qual profeta confrontou o rei Davi após o pecado com Bate-Seba?", opcoes: ["Natã", "Gade", "Samuel", "Elias"], respostaCorreta: 0, nivel: 'medio', mes: 10 },

    { pergunta: "Qual o nome do vale onde Josué pediu para o sol parar?", opcoes: ["Vale de Aijalom", "Vale de Elá", "Vale de Sidim", "Vale de Acor"], respostaCorreta: 0, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual o nome do pai de Noé?", opcoes: ["Matusalém", "Lameque", "Enoque", "Jerde"], respostaCorreta: 1, nivel: 'dificil', mes: 10 },
    { pergunta: "Quantos anos viveu Matusalém, o homem mais velho registrado na Bíblia?", opcoes: ["777 anos", "888 anos", "969 anos", "999 anos"], respostaCorreta: 2, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual o nome do rei de Tiro que forneceu cedros para a construção do templo de Salomão?", opcoes: ["Hiram", "Balaque", "Aquabe", "Ben-Hadade"], respostaCorreta: 0, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual o nome do monte onde ardia a sarça que não se consumia?", opcoes: ["Monte Sinai", "Monte Horebe", "Monte Sião", "Monte Nebo"], respostaCorreta: 1, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual o nome da mãe de João Batista?", opcoes: ["Maria", "Isabel", "Eros", "Salome"], respostaCorreta: 1, nivel: 'dificil', mes: 10 },
    { pergunta: "Quem foi o artífice principal encarregado da construção do Tabernáculo e dos utensílios sagrados?", opcoes: ["Bezalel", "Aoliabe", "Finias", "Itamar"], respostaCorreta: 0, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual o nome do rei de Judá que encontrou o livro da lei durante a reforma do templo?", opcoes: ["Ezequias", "Josias", "Jeosafá", "Joás"], respostaCorreta: 1, nivel: 'dificil', mes: 10 },
    { pergunta: "Qual profeta foi contemporâneo de Isaías e profetizou que o Messias nasceria em Belém?", opcoes: ["Miqueias", "Amós", "Oseias", "Sofonias"], respostaCorreta: 0, nivel: 'dificil', mes: 10 },
    { pergunta: "Obadias profetizou principalmente contra qual nação vizinha de Israel?", opcoes: ["Egito", "Assíria", "Edom", "Babilônia"], respostaCorreta: 2, nivel: 'dificil', mes: 10 },




    { pergunta: "Quem foi o homem mais forte descrito na Bíblia?", opcoes: ["Davi", "Sansão", "Golias", "Salomão"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Quem vendeu sua primogenitura por um prato de lentilhas?", opcoes: ["Jacó", "Esaú", "Isaque", "José"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Quem teve um sonho com uma escada que ia da terra até o céu?", opcoes: ["Abraão", "Jacó", "José", "Noé"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Quantos dias Jesus ficou no sepulcro antes de ressuscitar?", opcoes: ["1 dia", "2 dias", "3 dias", "7 dias"], respostaCorreta: 2, nivel: 'facil', mes: 11 },
    { pergunta: "Qual o nome da mãe terrena de Jesus?", opcoes: ["Isabel", "Maria", "Marta", "Magdalena"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Qual o nome do pai de João Batista?", opcoes: ["Zacarias", "José", "Simeão", "Levi"], respostaCorreta: 0, nivel: 'facil', mes: 11 },
    { pergunta: "Qual o livro que encerra o cânon da Bíblia Sagrada?", opcoes: ["Judas", "Apocalipse", "Atos", "Romanos"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Qual apóstolo ficou conhecido por duvidar da ressurreição até ver Jesus?", opcoes: ["Pedro", "João", "Tomé", "Filipe"], respostaCorreta: 2, nivel: 'facil', mes: 11 },
    { pergunta: "Qual o nome do gigante filisteu derrotado por Davi?", opcoes: ["Lobeque", "Golias", "Og", "Sicom"], respostaCorreta: 1, nivel: 'facil', mes: 11 },
    { pergunta: "Quem criou todas as coisas segundo o livro de Gênesis?", opcoes: ["Os anjos", "Deus", "O homem", "A natureza"], respostaCorreta: 1, nivel: 'facil', mes: 11 },

    { pergunta: "Qual o nome da esposa de Isaque?", opcoes: ["Rebeca", "Raquel", "Sara", "Lia"], respostaCorreta: 0, nivel: 'medio', mes: 11 },
    { pergunta: "Quem foi o profeta alimentado por corvos durante o período de seca?", opcoes: ["Elisha", "Elias", "Isaías", "Amós"], respostaCorreta: 1, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o nome da cidade onde Saulo (Paulo) se converteu após ver uma luz forte?", opcoes: ["Jerusalém", "Antioquia", "Damasco", "Tarso"], respostaCorreta: 2, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o rei de Israel que cometeu o erro de fazer um censo desnecessário do povo?", opcoes: ["Saul", "Davi", "Salomão", "Acabe"], respostaCorreta: 1, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o nome da montanha onde a arca de Noé pousou após o dilúvio?", opcoes: ["Monte Sinai", "Montes de Ararate", "Monte Carmelo", "Monte Nebo"], respostaCorreta: 1, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o profeta que recebeu ordem de Deus para casar com uma mulher infiel?", opcoes: ["Oseias", "Jeremias", "Ezequiel", "Joel"], respostaCorreta: 0, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o nome do rei que sucedeu a Salomão e cujo reino sofreu divisão?", opcoes: ["Roboão", "Jeroboão", "Ezequias", "Josias"], respostaCorreta: 0, nivel: 'medio', mes: 11 },
    { pergunta: "Quem era o copeiro do rei Artaxerxes que liderou a reconstrução dos muros de Jerusalém?", opcoes: ["Esdras", "Neemias", "Zorobabel", "Ageu"], respostaCorreta: 1, nivel: 'medio', mes: 11 },
    { pergunta: "Qual discípulo levou Natanael para conhecer Jesus?", opcoes: ["Pedro", "André", "Filipe", "Tiago"], respostaCorreta: 2, nivel: 'medio', mes: 11 },
    { pergunta: "Qual o nome da região onde Jesus transformou água em vinho?", opcoes: ["Cafarnaum", "Caná da Galileia", "Betânia", "Judeia"], respostaCorreta: 1, nivel: 'medio', mes: 11 },

    { pergunta: "Qual o nome do rio que passava pela Babilônia junto ao qual o profeta Daniel teve visões?", opcoes: ["Rio Eufrates", "Rio Tigre", "Rio Quebar", "Rio Ulai"], respostaCorreta: 2, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do rei assírio que sitiou Jerusalém durante o reinado de Ezequias?", opcoes: ["Senaqueribe", "Tiglate-Pileser", "Sargão", "Nabucodonosor"], respostaCorreta: 0, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do sumo sacerdote que escondeu o pequeno Joás para salvá-lo da rainha Atalia?", opcoes: ["Joiada", "Hilquias", "Zadoque", "Urias"], respostaCorreta: 0, nivel: 'dificil', mes: 11 },
    { pergunta: "Quantos portões tinha a muralha da Nova Jerusalém descrita no Apocalipse?", opcoes: ["4 portões", "7 portões", "10 portões", "12 portões"], respostaCorreta: 3, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do rei de Gerar que recolheu Sara pensando ser irmã de Abraão?", opcoes: ["Abimeleque", "Eglon", "Aquabe", "Faraó"], respostaCorreta: 0, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do filho de Davi que liderou uma grande conspiração e revolta para tomar o trono?", opcoes: ["Salomão", "Absalão", "Amnon", "Adonias"], respostaCorreta: 1, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome da profetisa idosa que louvou a Deus ao ver o menino Jesus no templo?", opcoes: ["Ana", "Hulda", "Débora", "Isabel"], respostaCorreta: 0, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do rei de Judá que reinou por apenas 3 meses e foi levado cativo por Nabucodonosor?", opcoes: ["Jeoaquim", "Jeoachaz", "Sedequias", "Manassés"], respostaCorreta: 1, nivel: 'dificil', mes: 11 },
    { pergunta: "Qual o nome do pai do rei Ezequias de Judá?", opcoes: ["Acaz", "Jotão", "Uzias", "Amasias"], respostaCorreta: 0, nivel: 'dificil', mes: 11 },
    { pergunta: "Na visão dos quatro carros de Zacarias, de entre que tipo de montanhas eles saíam?", opcoes: ["Montanhas de ouro", "Montanhas de bronze", "Montanhas de ferro", "Montanhas de pedra branca"], respostaCorreta: 1, nivel: 'dificil', mes: 11 },




    { pergunta: "Em qual cidade Jesus nasceu?", opcoes: ["Nazaré", "Belém", "Jerusalém", "Cafarnaum"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "Quem visitou o menino Jesus guiados por uma estrela?", opcoes: ["Os pastores", "Os reis magos", "Os anjos", "Os fariseus"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "Quem anunciou o nascimento de Jesus à virgem Maria?", opcoes: ["O anjo Gabriel", "O anjo Miguel", "João Batista", "José"], respostaCorreta: 0, nivel: 'facil', mes: 12 },
    { pergunta: "Qual o nome do pai adotivo de Jesus?", opcoes: ["Zacarias", "José", "Simeão", "Levi"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "Onde Jesus foi deitado logo após nascer?", opcoes: ["Em um berço de ouro", "Em uma manjedoura", "Em uma cama real", "Na casa de Maria"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "O que significa o nome profético 'Emanuel'?", opcoes: ["Deus conosco", "Príncipe da Paz", "Salvador do Mundo", "Rei dos Reis"], respostaCorreta: 0, nivel: 'facil', mes: 12 },
    { pergunta: "Quem soube do nascimento de Jesus através de anjos no campo à noite?", opcoes: ["Os reis magos", "Os pastores de ovelhas", "Os líderes religiosos", "O Faraó"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "Para qual país a família de Jesus fugiu de Herodes?", opcoes: ["Síria", "Egito", "Babilônia", "Grécia"], respostaCorreta: 1, nivel: 'facil', mes: 12 },
    { pergunta: "Qual rei mandou matar os meninos em Belém?", opcoes: ["Herodes o Grande", "Herodes Antipas", "Pôncio Pilatos", "César Augusto"], respostaCorreta: 0, nivel: 'facil', mes: 12 },
    { pergunta: "Em qual cidade Jesus passou sua infância?", opcoes: ["Belém", "Nazaré", "Jerusalém", "Jericó"], respostaCorreta: 1, nivel: 'facil', mes: 12 },

    { pergunta: "Qual sacerdote idoso segurou o bebê Jesus nos braços no templo?", opcoes: ["Simeão", "Zacarias", "Anas", "Caifás"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Qual o nome da profetisa idosa que louvava a Deus no templo?", opcoes: ["Ana", "Hulda", "Isabel", "Débora"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Qual imperador ordenou o recenseamento que levou Maria e José a Belém?", opcoes: ["César Augusto", "Tibério César", "Júlio César", "Nero"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Quantos dias após o nascimento Jesus foi apresentado no templo?", opcoes: ["7 dias", "8 dias", "40 dias", "30 dias"], respostaCorreta: 1, nivel: 'medio', mes: 12 },
    { pergunta: "Qual presente dos magos simbolizava a realeza?", opcoes: ["Ouro", "Incenso", "Mirra", "Prata"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Qual presente dos magos simbolizava a divindade e o sacerdócio?", opcoes: ["Incenso", "Ouro", "Mirra", "Linho"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Qual presente dos magos simbolizava a morte futura de Jesus?", opcoes: ["Mirra", "Ouro", "Incenso", "Bronze"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Quantos anos tinha Jesus quando debateu com os doutores no templo?", opcoes: ["12 anos", "10 anos", "15 anos", "30 anos"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Quem era o imperador romano no nascimento de Cristo?", opcoes: ["César Augusto", "Pilatos", "Cirênio", "Herodes"], respostaCorreta: 0, nivel: 'medio', mes: 12 },
    { pergunta: "Quem antecedeu Jesus preparando o caminho?", opcoes: ["João Batista", "Malaquias", "Elias", "Isaías"], respostaCorreta: 0, nivel: 'medio', mes: 12 },

    { pergunta: "Quem era o governador da Síria durante o recenseamento segundo Lucas?", opcoes: ["Cirênio (Quirino)", "Sérgio Paulo", "Pilatos", "Félix"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Quantas mulheres aparecem na genealogia de Jesus em Mateus?", opcoes: ["Quatro (Tamar, Raabe, Rute e a mulher de Urias)", "Apenas Maria", "Cinco", "Nenhuma"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Como se chama o ancestral chave na linhagem real de Davi até José?", opcoes: ["Matã / Jacó", "Natan", "Zorobabel", "Jeosafá"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Qual profeta predisse a matança dos inocentes em Belém?", opcoes: ["Jeremias", "Isaías", "Miqueias", "Oséias"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Qual anjo anunciou o nascimento de João Batista a Zacarias?", opcoes: ["Gabriel", "Miguel", "Rafael", "Uriel"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Qual profecia indicou aos magos que o Messias nasceria em Belém?", opcoes: ["Profecia de Miqueias", "Profecia de Isaías", "Profecia de Daniel", "Profecia de Jeremias"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Em qual região ficava Nazaré?", opcoes: ["Galileia", "Judeia", "Samaria", "Decápole"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Como é conhecido o cântico de Maria ao visitar Isabel?", opcoes: ["Magnificat", "Benedictus", "Nunc Dimittis", "Gloria"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Como é conhecido o cântico de Zacarias após o nascimento de João Batista?", opcoes: ["Benedictus", "Magnificat", "Gloria", "Hosana"], respostaCorreta: 0, nivel: 'dificil', mes: 12 },
    { pergunta: "Quantas gerações há em cada bloco da genealogia de Jesus segundo Mateus?", opcoes: ["14 gerações", "7 gerações", "12 gerações", "40 gerações"], respostaCorreta: 0, nivel: 'dificil', mes: 12 }
];